//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class adc
    {
        public Nullable<System.DateTime> TimeVal { get; set; }
        public Nullable<int> IndexZone { get; set; }
        public Nullable<int> IndexDevice { get; set; }
        public Nullable<int> ComputerID { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<double> ADC1 { get; set; }
        public Nullable<int> Status { get; set; }
        public System.Guid GUID { get; set; }
        public int TypeADC { get; set; }
    }
}
