//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authorities()
        {
            this.RelationDiv = new HashSet<RelationDiv>();
        }
    
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int ProgramID { get; set; }
        public Nullable<int> ProgramSubItemID { get; set; }
        public Nullable<int> aBrowse { get; set; }
        public Nullable<int> aInsert { get; set; }
        public Nullable<int> aEdit { get; set; }
        public Nullable<int> aDelete { get; set; }
        public Nullable<int> Archive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationDiv> RelationDiv { get; set; }
    }
}
