//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BindingItemsScenarios
    {
        public int ID_ScenariosTypes { get; set; }
        public int ID_ItemsScenarios { get; set; }
        public byte ID_Level { get; set; }
        public bool Def { get; set; }
        public int Sort { get; set; }
        public bool ReadOnly { get; set; }
        public string RegExp { get; set; }
        public Nullable<int> SortExp { get; set; }
    
        public virtual ReferenceItemsScenarios ReferenceItemsScenarios { get; set; }
        public virtual ReferenceScenariosTypes ReferenceScenariosTypes { get; set; }
    }
}
