//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BindingItemsDevScenarios
    {
        public int ID_ElementType { get; set; }
        public int ID_ItemsScenarios { get; set; }
        public int Sort { get; set; }
        public bool ReadOnly { get; set; }
    
        public virtual ReferenceItemsScenarios ReferenceItemsScenarios { get; set; }
    }
}
