//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BindingCommandScenarios
    {
        public int ID_ItemsScenarios { get; set; }
        public int ID_CommandScenarios { get; set; }
        public byte ID_Level { get; set; }
        public int Sort { get; set; }
        public bool Def { get; set; }
        public bool isNumber { get; set; }
    
        public virtual ReferenceCommandScenarios ReferenceCommandScenarios { get; set; }
        public virtual ReferenceItemsScenarios ReferenceItemsScenarios { get; set; }
    }
}
