//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cameras
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CamNumber { get; set; }
        public Nullable<int> MonNumber { get; set; }
        public Nullable<int> GType { get; set; }
        public Nullable<int> FAlertRecord { get; set; }
        public Nullable<int> RecTimeAfterAlarm { get; set; }
        public byte[] Settings { get; set; }
        public string IPCamParams { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> AutoTakeOff { get; set; }
        public Nullable<int> GIndex { get; set; }
        public string IPAddr { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
