//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFieldsValues
    {
        public int ID { get; set; }
        public int field_id { get; set; }
        public int owner { get; set; }
        public string value { get; set; }
    
        public virtual ClientFieldsNames ClientFieldsNames { get; set; }
        public virtual pList pList { get; set; }
    }
}
