//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComPorts
    {
        public int ID { get; set; }
        public int ComputerID { get; set; }
        public int Number { get; set; }
        public int Adaptor { get; set; }
        public int PrAdaptor { get; set; }
        public int PortType { get; set; }
        public string AdaptorAddress { get; set; }
        public string IPAddress { get; set; }
        public int Protokoltype { get; set; }
        public Nullable<int> TypeLine { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
        public Nullable<int> Baud { get; set; }
    }
}
