//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevCamerasItems
    {
        public System.Guid GUID { get; set; }
        public int ObjType { get; set; }
        public int GIndex { get; set; }
        public int CamIndex { get; set; }
        public Nullable<int> Param { get; set; }
        public Nullable<int> IsEventRec { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
