//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevItems
    {
        public int ID { get; set; }
        public int ComputerID { get; set; }
        public int DeviceID { get; set; }
        public int Address { get; set; }
        public int GIndex { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Nullable<int> GType { get; set; }
        public int ItemType { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Command { get; set; }
        public Nullable<int> TimeOutControl { get; set; }
        public Nullable<int> TimeOutConfig { get; set; }
        public Nullable<int> Config { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<int> IndexForContactId { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
