//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class drivers
    {
        public int ID { get; set; }
        public string name { get; set; }
        public int port { get; set; }
        public string IP { get; set; }
        public string mac { get; set; }
        public string files { get; set; }
        public string mainfile { get; set; }
        public string inifile { get; set; }
        public string parameters { get; set; }
        public string start_cmd { get; set; }
        public string stop_cmd { get; set; }
        public string install_cmd { get; set; }
        public string uninstall_cmd { get; set; }
        public string folder { get; set; }
    }
}
