//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dTypesElement
    {
        public int ID { get; set; }
        public int DeviceType { get; set; }
        public Nullable<int> DeviceVersion { get; set; }
        public Nullable<int> ElementType { get; set; }
        public string Name { get; set; }
        public int CountShl { get; set; }
        public int CountKey { get; set; }
        public int CountReader { get; set; }
        public string Comment { get; set; }
        public int EventGroupID { get; set; }
        public string DeviceVersionStr { get; set; }
        public Nullable<int> Property { get; set; }
        public Nullable<int> ElementsTypesGroupId { get; set; }
        public Nullable<int> SortingNum { get; set; }
    }
}
