//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dTypes
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountShl { get; set; }
        public Nullable<int> CountKey { get; set; }
        public Nullable<int> CountReader { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Face { get; set; }
        public Nullable<int> Icon { get; set; }
        public Nullable<int> ProtokolType { get; set; }
        public Nullable<int> Interfaces { get; set; }
        public string WorkLib { get; set; }
    }
}
