//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DvsMass
    {
        public int ID { get; set; }
        public byte IconGroup { get; set; }
        public Nullable<int> GroupSort { get; set; }
        public int Number { get; set; }
        public int Left { get; set; }
        public int Top { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public bool LargeIcon { get; set; }
        public Nullable<int> NumberRelation { get; set; }
        public byte[] ResourceIco { get; set; }
        public Nullable<int> ResWidth { get; set; }
        public Nullable<int> ResHeight { get; set; }
        public Nullable<int> ResCountIco { get; set; }
        public Nullable<bool> DefaultLargeIcon { get; set; }
        public string Description { get; set; }
    }
}
