//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventOnModificationData
    {
        public int ID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ID_Application { get; set; }
        public int UpdateStatus { get; set; }
        public string AGuid { get; set; }
        public Nullable<int> ID_Subj { get; set; }
        public string Subj { get; set; }
        public string AData { get; set; }
    
        public virtual ApplicationModifData ApplicationModifData { get; set; }
    }
}
