//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Event { get; set; }
        public string CharID { get; set; }
        public string Contents { get; set; }
        public string Comment { get; set; }
        public Nullable<int> RealEvent { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> FormatView { get; set; }
        public Nullable<int> SoundNumber { get; set; }
        public Nullable<int> AlarmLevel { get; set; }
        public Nullable<int> GpEvent { get; set; }
        public Nullable<int> EventsCategoryID { get; set; }
        public Nullable<int> IsAlarm { get; set; }
    }
}
