//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvReply
    {
        public int ID { get; set; }
        public int ComputerID { get; set; }
        public int Source { get; set; }
        public int EventType { get; set; }
        public int UnitID { get; set; }
        public int ScriptID { get; set; }
        public Nullable<int> Data { get; set; }
        public Nullable<int> DataType { get; set; }
    }
}
