//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixVersionRsLine
    {
        public int ID_RsLine { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<int> DeviceVersionOld { get; set; }
        public Nullable<int> DeviceVersionNew { get; set; }
        public Nullable<System.DateTime> ChangeDateTme { get; set; }
    }
}
