//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrAccess()
        {
            this.Kone_DopAccess = new HashSet<Kone_DopAccess>();
            this.Kone_CopAccess = new HashSet<Kone_CopAccess>();
        }
    
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int Mode { get; set; }
        public int AccessID { get; set; }
        public Nullable<int> Config { get; set; }
        public int TimeZone { get; set; }
        public Nullable<int> Antipassback { get; set; }
        public Nullable<System.DateTime> PardonTime { get; set; }
        public Nullable<int> ConfirmID { get; set; }
        public Nullable<int> ConfirmID2 { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<int> CodeType { get; set; }
        public string Code { get; set; }
        public Nullable<int> Config2 { get; set; }
        public Nullable<int> PswAddCode { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kone_DopAccess> Kone_DopAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kone_CopAccess> Kone_CopAccess { get; set; }
    }
}
