//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Flags { get; set; }
        public string GUID_1C { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
        public int Flags2 { get; set; }
        public Nullable<int> isTemplate { get; set; }
    }
}
