//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class GsmSettings
    {
        public int ID { get; set; }
        public int RsLinesID { get; set; }
        public string Apn { get; set; }
        public string Login { get; set; }
        public string Passw { get; set; }
        public string SmtpServer { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public string SmtpLogin { get; set; }
        public string SmtpPassw { get; set; }
        public string SmtpMailFrom { get; set; }
        public string PopServer { get; set; }
        public Nullable<int> PopPort { get; set; }
        public string PopLogin { get; set; }
        public string PopPassw { get; set; }
    }
}
