//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kone_AllAccessMask
    {
        public int ID { get; set; }
        public short Floor { get; set; }
        public short SF { get; set; }
        public short SR { get; set; }
        public short DF { get; set; }
        public short DR { get; set; }
    
        public virtual Kone_DOPGlobalDefaultAccessMask Kone_DOPGlobalDefaultAccessMask { get; set; }
    }
}
