//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kone_COP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kone_COP()
        {
            this.Kone_CopAccess = new HashSet<Kone_CopAccess>();
            this.Kone_COPSpecificMask = new HashSet<Kone_COPSpecificMask>();
        }
    
        public int ID { get; set; }
        public int ID_KGS { get; set; }
        public int ID_AcessPoint { get; set; }
        public int elevator_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> open_timeout { get; set; }
    
        public virtual AcessPoint AcessPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kone_CopAccess> Kone_CopAccess { get; set; }
        public virtual Kone_KGS Kone_KGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kone_COPSpecificMask> Kone_COPSpecificMask { get; set; }
    }
}
