//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kone_COPSpecificMask
    {
        public int ID_Elevator { get; set; }
        public int ID { get; set; }
        public int CopSpecificSystemState { get; set; }
    
        public virtual Kone_COP Kone_COP { get; set; }
    }
}
