//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kone_DOPGlobalDefaultAccessMask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kone_DOPGlobalDefaultAccessMask()
        {
            this.Kone_AllAccessMask = new HashSet<Kone_AllAccessMask>();
        }
    
        public int ID_KGS { get; set; }
        public int ID { get; set; }
        public short SystemState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kone_AllAccessMask> Kone_AllAccessMask { get; set; }
        public virtual Kone_KGS Kone_KGS { get; set; }
    }
}
