//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kone_DOP
    {
        public int ID { get; set; }
        public int ID_KGS { get; set; }
        public int ID_AcessPoint { get; set; }
        public int dop_id { get; set; }
        public int dop_floor_id { get; set; }
        public Nullable<int> open_timeout { get; set; }
    
        public virtual AcessPoint AcessPoint { get; set; }
        public virtual Kone_KGS Kone_KGS { get; set; }
    }
}
