//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int ID { get; set; }
        public Nullable<int> tpChange { get; set; }
        public string OperatorName { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string ComputerName { get; set; }
        public Nullable<int> ComputerIP { get; set; }
        public Nullable<System.DateTime> TimeVal { get; set; }
        public byte[] RuquestDATA { get; set; }
        public Nullable<int> Reserv0 { get; set; }
        public Nullable<int> Reserv1 { get; set; }
        public string Reserv2 { get; set; }
    }
}
