//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_alarm
    {
        public Nullable<System.DateTime> Time0 { get; set; }
        public Nullable<int> NumCom { get; set; }
        public Nullable<int> IDComp { get; set; }
        public Nullable<int> Operator0 { get; set; }
        public string OperatorName { get; set; }
        public string EventName { get; set; }
        public string ZoneName { get; set; }
        public string ObjectName { get; set; }
        public int Event { get; set; }
        public Nullable<int> AddrCOM { get; set; }
        public Nullable<int> Address { get; set; }
        public Nullable<int> Object { get; set; }
        public string Action1 { get; set; }
        public Nullable<System.DateTime> Time1 { get; set; }
        public Nullable<int> Operator1 { get; set; }
        public string Action2 { get; set; }
        public Nullable<System.DateTime> Time2 { get; set; }
        public Nullable<int> Operator2 { get; set; }
        public string Action3 { get; set; }
        public Nullable<System.DateTime> Time3 { get; set; }
        public Nullable<int> Operator3 { get; set; }
        public string Action4 { get; set; }
        public Nullable<System.DateTime> Time4 { get; set; }
        public Nullable<int> Operator4 { get; set; }
        public string Action5 { get; set; }
        public Nullable<System.DateTime> Time5 { get; set; }
        public Nullable<int> Operator5 { get; set; }
        public string Action6 { get; set; }
        public Nullable<System.DateTime> Time6 { get; set; }
        public Nullable<int> Operator6 { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> DoorID { get; set; }
        public Nullable<int> ZoneType { get; set; }
        public Nullable<int> AccessZoneIndex { get; set; }
        public Nullable<int> VEvent { get; set; }
        public Nullable<int> ZReserv { get; set; }
        public Nullable<int> Zone { get; set; }
        public Nullable<int> IndexZone { get; set; }
        public Nullable<int> tpIndex { get; set; }
        public System.Guid GUID { get; set; }
    }
}
