//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_Elm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Map_Elm()
        {
            this.map_indicators = new HashSet<map_indicators>();
        }
    
        public int ID { get; set; }
        public int MapID { get; set; }
        public int GType { get; set; }
        public Nullable<int> Num { get; set; }
        public int UnitID { get; set; }
        public Nullable<int> PictureCount { get; set; }
        public byte[] Pictures { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<int> Link2Obj { get; set; }
        public Nullable<System.Guid> ApplicationGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<map_indicators> map_indicators { get; set; }
    }
}
