//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapElements
    {
        public int ID { get; set; }
        public int table { get; set; }
        public int map_id { get; set; }
        public int item_id { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public double rotate { get; set; }
        public double scale { get; set; }
        public string state_name { get; set; }
        public int item_type { get; set; }
        public int item_color { get; set; }
        public int value_off { get; set; }
        public int value_pos { get; set; }
        public int text_off { get; set; }
        public int text_pos { get; set; }
        public double value_x { get; set; }
        public double value_y { get; set; }
    }
}
