//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapIndicatorsDefault
    {
        public int ID_Indicator { get; set; }
        public double RangeMin { get; set; }
        public double RangeMax { get; set; }
        public int RangeColor { get; set; }
        public int StatusRange { get; set; }
    }
}
