//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class pBioParams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pBioParams()
        {
            this.RSBioParams = new HashSet<RSBioParams>();
        }
    
        public int ID { get; set; }
        public int Device_Type { get; set; }
        public int Master { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public int Type { get; set; }
        public Nullable<float> Min { get; set; }
        public Nullable<float> Max { get; set; }
        public string DefValue { get; set; }
        public string Values { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSBioParams> RSBioParams { get; set; }
    }
}
