//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class pBioAccess
    {
        public int ID { get; set; }
        public int ID_pMark { get; set; }
        public int GType { get; set; }
        public string BioTemplate2 { get; set; }
    
        public virtual pMark pMark { get; set; }
    }
}
