//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsPhotos
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public byte[] PhotoDescriptor { get; set; }
        public Nullable<int> DescriptorType { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> PhotoNum { get; set; }
    }
}
