//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_numbers
    {
        public int ID { get; set; }
        public string phone_number { get; set; }
        public string ip { get; set; }
        public Nullable<int> port { get; set; }
        public string email { get; set; }
        public Nullable<int> translateProtocol { get; set; }
        public string password { get; set; }
        public string description { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
