//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class pListNetPorts
    {
        public int ID { get; set; }
        public string NAME_TASK { get; set; }
        public Nullable<int> PORT_TASK { get; set; }
        public string COMMENT { get; set; }
    }
}
