//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class pMaps
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public int GIndex { get; set; }
        public int ComputerID { get; set; }
        public Nullable<int> PlanChild { get; set; }
        public Nullable<int> Spack { get; set; }
        public byte[] Contents { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> design_width { get; set; }
        public Nullable<int> design_height { get; set; }
        public Nullable<double> design_scale { get; set; }
        public string SchemaExt { get; set; }
        public Nullable<System.Guid> ApplicationGuid { get; set; }
    }
}
