//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeVal { get; set; }
        public string IP { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string OperatorName { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public byte[] Query { get; set; }
        public byte[] Parameters { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
    }
}
