//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RdrAccessPoint
    {
        public int ID { get; set; }
        public int ReaderID { get; set; }
        public int Mode { get; set; }
        public int AccessPointID { get; set; }
        public int ModeAcess { get; set; }
        public Nullable<int> PenalID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
