//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reasons
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string Operator { get; set; }
        public Nullable<int> GoodTime { get; set; }
        public Nullable<int> BUTNOTCALC { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public Nullable<int> ReasonID { get; set; }
    }
}
