//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceScenariosTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferenceScenariosTypes()
        {
            this.BindingItemsScenarios = new HashSet<BindingItemsScenarios>();
            this.ScenariosDevice = new HashSet<ScenariosDevice>();
            this.ScenariosFilterDevice = new HashSet<ScenariosFilterDevice>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LatName { get; set; }
        public bool Def { get; set; }
        public int Sort { get; set; }
        public int ImageIndex { get; set; }
        public int ImageIDScen { get; set; }
        public int ImageIDStep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingItemsScenarios> BindingItemsScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenariosDevice> ScenariosDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenariosFilterDevice> ScenariosFilterDevice { get; set; }
    }
}
