//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceItemsScenarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferenceItemsScenarios()
        {
            this.BindingCommandScenarios = new HashSet<BindingCommandScenarios>();
            this.BindingItemsDevScenarios = new HashSet<BindingItemsDevScenarios>();
            this.BindingItemsScenarios = new HashSet<BindingItemsScenarios>();
            this.ValueDevItemsScenarios = new HashSet<ValueDevItemsScenarios>();
            this.ValueItemsScenarios = new HashSet<ValueItemsScenarios>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LatName { get; set; }
        public string TypeValue { get; set; }
        public string TypeContrl { get; set; }
        public string Code { get; set; }
        public string RegExp { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public bool isRefresh { get; set; }
        public string ExpText { get; set; }
        public Nullable<decimal> Increment { get; set; }
        public bool IncrFixed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingCommandScenarios> BindingCommandScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingItemsDevScenarios> BindingItemsDevScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingItemsScenarios> BindingItemsScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueDevItemsScenarios> ValueDevItemsScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueItemsScenarios> ValueItemsScenarios { get; set; }
    }
}
