//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationsListCar
    {
        public int ID { get; set; }
        public int IdList { get; set; }
        public int IdCar { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    
        public virtual pCar pCar { get; set; }
        public virtual pList pList { get; set; }
    }
}
