//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSBioParams
    {
        public int ID { get; set; }
        public int ID_Device { get; set; }
        public int ID_Param { get; set; }
        public string Value { get; set; }
    
        public virtual pBioParams pBioParams { get; set; }
        public virtual RSLines RSLines { get; set; }
    }
}
