//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSLines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSLines()
        {
            this.Kone_KGS = new HashSet<Kone_KGS>();
            this.RSBioParams = new HashSet<RSBioParams>();
        }
    
        public int ID { get; set; }
        public int GIndex { get; set; }
        public int ComPortID { get; set; }
        public int PKUID { get; set; }
        public int GLineNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Broadcast { get; set; }
        public Nullable<int> DeviceVersion { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string GATEWAY { get; set; }
        public string SUBMASK { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> UseDHCP { get; set; }
        public string IdContactName { get; set; }
        public Nullable<int> IdDevice { get; set; }
        public int DeviceInterface { get; set; }
        public Nullable<int> IndexForContactId { get; set; }
        public string DeviceTypeBIO { get; set; }
        public Nullable<int> AbonentType { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kone_KGS> Kone_KGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSBioParams> RSBioParams { get; set; }
    }
}
