//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenariosDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenariosDevice()
        {
            this.BindingConditionStepScen = new HashSet<BindingConditionStepScen>();
            this.BindingGrObjectsStepScen = new HashSet<BindingGrObjectsStepScen>();
            this.BindingObjectsStepScen = new HashSet<BindingObjectsStepScen>();
            this.ScenariosDevice1 = new HashSet<ScenariosDevice>();
            this.ValueItemsScenarios = new HashSet<ValueItemsScenarios>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<int> ID_Parent { get; set; }
        public int ID_ScenariosTypes { get; set; }
        public int ID_Device { get; set; }
        public int DeviceType { get; set; }
        public int ID_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingConditionStepScen> BindingConditionStepScen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingGrObjectsStepScen> BindingGrObjectsStepScen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BindingObjectsStepScen> BindingObjectsStepScen { get; set; }
        public virtual ReferenceScenariosTypes ReferenceScenariosTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenariosDevice> ScenariosDevice1 { get; set; }
        public virtual ScenariosDevice ScenariosDevice2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueItemsScenarios> ValueItemsScenarios { get; set; }
    }
}
