//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenariosFilterDevice
    {
        public int DeviceType { get; set; }
        public int ElementType { get; set; }
        public int ID_ScenariosType { get; set; }
        public int DeviceVersion { get; set; }
        public int NumberDevItem { get; set; }
        public int ParentDevType { get; set; }
    
        public virtual ReferenceScenariosTypes ReferenceScenariosTypes { get; set; }
    }
}
