//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings_Value
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int id_comp { get; set; }
        public int Groups_Id { get; set; }
        public byte[] settings { get; set; }
        public string Value { get; set; }
        public int TypeValue { get; set; }
        public Nullable<int> Reserve { get; set; }
    
        public virtual Settings_group Settings_group { get; set; }
    }
}
