//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsGatesParams
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Passw { get; set; }
        public string SenderName { get; set; }
        public string InboundPhone { get; set; }
        public int RsLinesId { get; set; }
        public string ProxyServer { get; set; }
        public int ProxyPort { get; set; }
        public string ProxyLogin { get; set; }
        public string ProxyPassw { get; set; }
    }
}
