//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSLCertificate
    {
        public int ID { get; set; }
        public byte[] RootCA { get; set; }
        public byte[] CAKey { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Reserv { get; set; }
    }
}
