//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class states_item
    {
        public int item_type { get; set; }
        public int item_id { get; set; }
        public System.DateTime tmvl { get; set; }
        public Nullable<int> state_item { get; set; }
        public Nullable<int> comps_id { get; set; }
        public Nullable<int> id_owner { get; set; }
    }
}
