//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public int Gtype { get; set; }
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public int DefaultValue { get; set; }
        public int Required { get; set; }
        public string Comments { get; set; }
        public string Hint { get; set; }
        public byte[] List { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> SysOrder { get; set; }
    }
}
