//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysParam
    {
        public int Num { get; set; }
        public int ID { get; set; }
        public int ComputerID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Gtype { get; set; }
        public Nullable<int> GValue { get; set; }
        public Nullable<int> Required { get; set; }
        public string Comment { get; set; }
    }
}
