//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemObjects
    {
        public int GIndex { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public int ExState { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public int Reserve1 { get; set; }
        public int Reserve2 { get; set; }
        public int Reserve3 { get; set; }
        public int Reserve4 { get; set; }
    }
}
