//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tKBPenals
    {
        public int ID { get; set; }
        public int GIndex { get; set; }
        public int ID_Section { get; set; }
        public int BIndex { get; set; }
        public string Box_Name { get; set; }
        public Nullable<int> State { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IndexForContactID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
        public Nullable<int> pListID { get; set; }
    }
}
