//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tKeyBoxes
    {
        public int ID { get; set; }
        public int GIndex { get; set; }
        public int IdComPort { get; set; }
        public Nullable<int> Adress { get; set; }
        public string DevName { get; set; }
        public int SectionsQTY { get; set; }
        public string Ver { get; set; }
        public string Comment { get; set; }
        public int CompID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string AccessKey { get; set; }
        public Nullable<int> IndexForContactID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
