//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPersonalStuff
    {
        public int ID { get; set; }
        public int PListID { get; set; }
        public int PenalID { get; set; }
        public int ReferenceBookID { get; set; }
    
        public virtual pList pList { get; set; }
        public virtual tReferenceBook tReferenceBook { get; set; }
    }
}
