//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPStuffPhoto
    {
        public int ID { get; set; }
        public int IDPLIST { get; set; }
        public byte[] picture { get; set; }
        public Nullable<int> Spack { get; set; }
    
        public virtual pList pList { get; set; }
    }
}
