//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPStuffLogData
    {
        public System.Guid GUID { get; set; }
        public int PenalID { get; set; }
        public int PListID { get; set; }
        public int ReferenceBookID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public System.DateTime TimeVal { get; set; }
        public string FIO { get; set; }
        public string PStuffName { get; set; }
    }
}
