//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeShlDevice
    {
        public int ID { get; set; }
        public int DeviceType { get; set; }
        public string DeviceTypeName { get; set; }
        public int DeviceVersion { get; set; }
        public int NumShBegin { get; set; }
        public int NumShStop { get; set; }
        public int ElementType { get; set; }
        public int ShlType { get; set; }
    }
}
