//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ChangeLogForDB
    {
        public System.Guid ID { get; set; }
        public System.DateTime timeVal { get; set; }
        public int state_record { get; set; }
        public string table_name { get; set; }
        public int ValueId { get; set; }
        public int OperatorId { get; set; }
        public string InsideSystem { get; set; }
        public string xml_data { get; set; }
        public int Num { get; set; }
        public string Workstation { get; set; }
    }
}
