//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionDB
    {
        public int Num { get; set; }
        public string Version { get; set; }
        public string VersionDataBase { get; set; }
        public int CountTable { get; set; }
        public string Info { get; set; }
        public int Rezerv1 { get; set; }
        public string GUID_DB { get; set; }
    }
}
