//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoEvents
    {
        public System.Guid GUID { get; set; }
        public int TypeObj { get; set; }
        public int GIndex { get; set; }
        public int Event { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int FileSize { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Param { get; set; }
        public System.Guid PathID { get; set; }
        public Nullable<int> NumRec { get; set; }
        public Nullable<int> NumPart { get; set; }
        public Nullable<byte> ProtectedRec { get; set; }
    }
}
