//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoRecognizeChannels
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int VideoInspectorID { get; set; }
        public int Number { get; set; }
        public int GIndex { get; set; }
        public int ProfileID { get; set; }
        public int CameraID { get; set; }
        public Nullable<int> ChannelMode { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
