//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInspTypes
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> vInspType { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Flags { get; set; }
    }
}
