//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInsp
    {
        public int ID { get; set; }
        public int ComputerID { get; set; }
        public string Name { get; set; }
        public string TCP_IP { get; set; }
        public Nullable<int> VinspType { get; set; }
        public Nullable<int> ActiveX { get; set; }
        public string CompName { get; set; }
        public Nullable<int> GIndex { get; set; }
        public string vInspParams { get; set; }
        public string ArchivePath { get; set; }
        public Nullable<int> IsSecure { get; set; }
        public byte[] Settings { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Workstation { get; set; }
    }
}
