//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class weightcamera
    {
        public int ID { get; set; }
        public int door { get; set; }
        public int weightterminal { get; set; }
        public int weight0 { get; set; }
        public int weightdiscret { get; set; }
        public int deltaweightstable { get; set; }
        public int durationdooropen { get; set; }
        public int durationdooropenclose { get; set; }
        public int timefilter { get; set; }
        public int timestep { get; set; }
        public int minpersonweight { get; set; }
    }
}
